// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: proto/rpcca_rpc.proto

package rpcserver

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{0}
}

type SimpleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleReply) Reset() {
	*x = SimpleReply{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleReply) ProtoMessage() {}

func (x *SimpleReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleReply.ProtoReflect.Descriptor instead.
func (*SimpleReply) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleReply) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type Int64Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64Reply) Reset() {
	*x = Int64Reply{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Reply) ProtoMessage() {}

func (x *Int64Reply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Reply.ProtoReflect.Descriptor instead.
func (*Int64Reply) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *Int64Reply) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type DateFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lte           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=lte,proto3" json:"lte,omitempty"`
	Gte           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=gte,proto3" json:"gte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateFilter) Reset() {
	*x = DateFilter{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateFilter) ProtoMessage() {}

func (x *DateFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateFilter.ProtoReflect.Descriptor instead.
func (*DateFilter) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *DateFilter) GetLte() *timestamppb.Timestamp {
	if x != nil {
		return x.Lte
	}
	return nil
}

func (x *DateFilter) GetGte() *timestamppb.Timestamp {
	if x != nil {
		return x.Gte
	}
	return nil
}

type CertFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilterFields   []*KeyValueInfo        `protobuf:"bytes,1,rep,name=filter_fields,json=filterFields,proto3" json:"filter_fields,omitempty"`
	OrFilterFields []*KeyValueInfo        `protobuf:"bytes,2,rep,name=or_filter_fields,json=orFilterFields,proto3" json:"or_filter_fields,omitempty"`
	Sans           []*San                 `protobuf:"bytes,3,rep,name=sans,proto3" json:"sans,omitempty"`
	NotBefore      *DateFilter            `protobuf:"bytes,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter       *DateFilter            `protobuf:"bytes,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Limit          int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy        string                 `protobuf:"bytes,8,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	OrderDirection int32                  `protobuf:"varint,9,opt,name=order_direction,json=orderDirection,proto3" json:"order_direction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CertFilter) Reset() {
	*x = CertFilter{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertFilter) ProtoMessage() {}

func (x *CertFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertFilter.ProtoReflect.Descriptor instead.
func (*CertFilter) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *CertFilter) GetFilterFields() []*KeyValueInfo {
	if x != nil {
		return x.FilterFields
	}
	return nil
}

func (x *CertFilter) GetOrFilterFields() []*KeyValueInfo {
	if x != nil {
		return x.OrFilterFields
	}
	return nil
}

func (x *CertFilter) GetSans() []*San {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *CertFilter) GetNotBefore() *DateFilter {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertFilter) GetNotAfter() *DateFilter {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CertFilter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CertFilter) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *CertFilter) GetOrderDirection() int32 {
	if x != nil {
		return x.OrderDirection
	}
	return 0
}

type San struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *San) Reset() {
	*x = San{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *San) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*San) ProtoMessage() {}

func (x *San) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use San.ProtoReflect.Descriptor instead.
func (*San) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *San) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *San) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type KeyValueInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueInfo) Reset() {
	*x = KeyValueInfo{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueInfo) ProtoMessage() {}

func (x *KeyValueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueInfo.ProtoReflect.Descriptor instead.
func (*KeyValueInfo) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *KeyValueInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValueInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BasicConstraints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCa          bool                   `protobuf:"varint,1,opt,name=is_ca,json=isCa,proto3" json:"is_ca,omitempty"`
	PathLength    int32                  `protobuf:"varint,2,opt,name=path_length,json=pathLength,proto3" json:"path_length,omitempty"`
	IsCritical    bool                   `protobuf:"varint,3,opt,name=is_critical,json=isCritical,proto3" json:"is_critical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicConstraints) Reset() {
	*x = BasicConstraints{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicConstraints) ProtoMessage() {}

func (x *BasicConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicConstraints.ProtoReflect.Descriptor instead.
func (*BasicConstraints) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *BasicConstraints) GetIsCa() bool {
	if x != nil {
		return x.IsCa
	}
	return false
}

func (x *BasicConstraints) GetPathLength() int32 {
	if x != nil {
		return x.PathLength
	}
	return 0
}

func (x *BasicConstraints) GetIsCritical() bool {
	if x != nil {
		return x.IsCritical
	}
	return false
}

type CertImportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaName        string                 `protobuf:"bytes,1,opt,name=ca_name,json=caName,proto3" json:"ca_name,omitempty"`
	CertPem       string                 `protobuf:"bytes,2,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	Metadata      []*KeyValueInfo        `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertImportRequest) Reset() {
	*x = CertImportRequest{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertImportRequest) ProtoMessage() {}

func (x *CertImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertImportRequest.ProtoReflect.Descriptor instead.
func (*CertImportRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *CertImportRequest) GetCaName() string {
	if x != nil {
		return x.CaName
	}
	return ""
}

func (x *CertImportRequest) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CertImportRequest) GetMetadata() []*KeyValueInfo {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CertRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Pkcs10            string                 `protobuf:"bytes,1,opt,name=pkcs10,proto3" json:"pkcs10,omitempty"`
	CaName            string                 `protobuf:"bytes,2,opt,name=ca_name,json=caName,proto3" json:"ca_name,omitempty"`
	Sans              []*San                 `protobuf:"bytes,3,rep,name=sans,proto3" json:"sans,omitempty"`
	NotBefore         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	KeySize           int32                  `protobuf:"varint,8,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	CommonName        string                 `protobuf:"bytes,9,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	ExtendedKeyUsage  []string               `protobuf:"bytes,11,rep,name=extended_key_usage,json=extendedKeyUsage,proto3" json:"extended_key_usage,omitempty"`
	TemplateName      string                 `protobuf:"bytes,12,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Kvinfo            []*KeyValueInfo        `protobuf:"bytes,13,rep,name=kvinfo,proto3" json:"kvinfo,omitempty"`
	KeyConstraintsStr []string               `protobuf:"bytes,14,rep,name=KeyConstraintsStr,proto3" json:"KeyConstraintsStr,omitempty"`
	BasicConstraints  *BasicConstraints      `protobuf:"bytes,15,opt,name=basic_constraints,json=basicConstraints,proto3" json:"basic_constraints,omitempty"`
	KeyType           string                 `protobuf:"bytes,16,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CertRequest) Reset() {
	*x = CertRequest{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRequest) ProtoMessage() {}

func (x *CertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRequest.ProtoReflect.Descriptor instead.
func (*CertRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *CertRequest) GetPkcs10() string {
	if x != nil {
		return x.Pkcs10
	}
	return ""
}

func (x *CertRequest) GetCaName() string {
	if x != nil {
		return x.CaName
	}
	return ""
}

func (x *CertRequest) GetSans() []*San {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *CertRequest) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertRequest) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertRequest) GetKeySize() int32 {
	if x != nil {
		return x.KeySize
	}
	return 0
}

func (x *CertRequest) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *CertRequest) GetExtendedKeyUsage() []string {
	if x != nil {
		return x.ExtendedKeyUsage
	}
	return nil
}

func (x *CertRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *CertRequest) GetKvinfo() []*KeyValueInfo {
	if x != nil {
		return x.Kvinfo
	}
	return nil
}

func (x *CertRequest) GetKeyConstraintsStr() []string {
	if x != nil {
		return x.KeyConstraintsStr
	}
	return nil
}

func (x *CertRequest) GetBasicConstraints() *BasicConstraints {
	if x != nil {
		return x.BasicConstraints
	}
	return nil
}

func (x *CertRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type CertificateFingerprint struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CertFingerprint string                 `protobuf:"bytes,1,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CertificateFingerprint) Reset() {
	*x = CertificateFingerprint{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateFingerprint) ProtoMessage() {}

func (x *CertificateFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateFingerprint.ProtoReflect.Descriptor instead.
func (*CertificateFingerprint) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *CertificateFingerprint) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

type Certificate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommonName      string                 `protobuf:"bytes,1,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	IssuerDn        string                 `protobuf:"bytes,2,opt,name=issuer_dn,json=issuerDn,proto3" json:"issuer_dn,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	NotBefore       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	CertSerial      string                 `protobuf:"bytes,6,opt,name=cert_serial,json=certSerial,proto3" json:"cert_serial,omitempty"`
	CertFingerprint string                 `protobuf:"bytes,7,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"`
	Sans            []*San                 `protobuf:"bytes,8,rep,name=sans,proto3" json:"sans,omitempty"`
	SigAlgo         string                 `protobuf:"bytes,9,opt,name=sig_algo,json=sigAlgo,proto3" json:"sig_algo,omitempty"`
	KeyLength       int32                  `protobuf:"varint,10,opt,name=key_length,json=keyLength,proto3" json:"key_length,omitempty"`
	CaName          string                 `protobuf:"bytes,11,opt,name=ca_name,json=caName,proto3" json:"ca_name,omitempty"`
	TemplateName    string                 `protobuf:"bytes,12,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	CertString      string                 `protobuf:"bytes,13,opt,name=cert_string,json=certString,proto3" json:"cert_string,omitempty"`
	Cdps            []string               `protobuf:"bytes,14,rep,name=cdps,proto3" json:"cdps,omitempty"`
	Metadata        []*KeyValueInfo        `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty"`
	IssuedDn        string                 `protobuf:"bytes,16,opt,name=issued_dn,json=issuedDn,proto3" json:"issued_dn,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *Certificate) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *Certificate) GetIssuerDn() string {
	if x != nil {
		return x.IssuerDn
	}
	return ""
}

func (x *Certificate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Certificate) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *Certificate) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *Certificate) GetCertSerial() string {
	if x != nil {
		return x.CertSerial
	}
	return ""
}

func (x *Certificate) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

func (x *Certificate) GetSans() []*San {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *Certificate) GetSigAlgo() string {
	if x != nil {
		return x.SigAlgo
	}
	return ""
}

func (x *Certificate) GetKeyLength() int32 {
	if x != nil {
		return x.KeyLength
	}
	return 0
}

func (x *Certificate) GetCaName() string {
	if x != nil {
		return x.CaName
	}
	return ""
}

func (x *Certificate) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *Certificate) GetCertString() string {
	if x != nil {
		return x.CertString
	}
	return ""
}

func (x *Certificate) GetCdps() []string {
	if x != nil {
		return x.Cdps
	}
	return nil
}

func (x *Certificate) GetMetadata() []*KeyValueInfo {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Certificate) GetIssuedDn() string {
	if x != nil {
		return x.IssuedDn
	}
	return ""
}

type CertificateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          []*Certificate         `protobuf:"bytes,1,rep,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateList) Reset() {
	*x = CertificateList{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateList) ProtoMessage() {}

func (x *CertificateList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateList.ProtoReflect.Descriptor instead.
func (*CertificateList) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *CertificateList) GetCert() []*Certificate {
	if x != nil {
		return x.Cert
	}
	return nil
}

type RevokeCertRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CaName           string                 `protobuf:"bytes,1,opt,name=ca_name,json=caName,proto3" json:"ca_name,omitempty"`
	CertFingerprint  string                 `protobuf:"bytes,2,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"`
	RevocationReason string                 `protobuf:"bytes,3,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"`
	RevocationDate   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=revocation_date,json=revocationDate,proto3" json:"revocation_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevokeCertRequest) Reset() {
	*x = RevokeCertRequest{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertRequest) ProtoMessage() {}

func (x *RevokeCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertRequest.ProtoReflect.Descriptor instead.
func (*RevokeCertRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeCertRequest) GetCaName() string {
	if x != nil {
		return x.CaName
	}
	return ""
}

func (x *RevokeCertRequest) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

func (x *RevokeCertRequest) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

func (x *RevokeCertRequest) GetRevocationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RevocationDate
	}
	return nil
}

type KeyRetreivalRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CertFingerprint string                 `protobuf:"bytes,1,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"`
	PassphraseHash  string                 `protobuf:"bytes,2,opt,name=passphrase_hash,json=passphraseHash,proto3" json:"passphrase_hash,omitempty"` // SHA-2 hash of the passphrase
	OutFormat       int32                  `protobuf:"varint,3,opt,name=out_format,json=outFormat,proto3" json:"out_format,omitempty"`
	CaName          string                 `protobuf:"bytes,4,opt,name=ca_name,json=caName,proto3" json:"ca_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KeyRetreivalRequest) Reset() {
	*x = KeyRetreivalRequest{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRetreivalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRetreivalRequest) ProtoMessage() {}

func (x *KeyRetreivalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRetreivalRequest.ProtoReflect.Descriptor instead.
func (*KeyRetreivalRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *KeyRetreivalRequest) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

func (x *KeyRetreivalRequest) GetPassphraseHash() string {
	if x != nil {
		return x.PassphraseHash
	}
	return ""
}

func (x *KeyRetreivalRequest) GetOutFormat() int32 {
	if x != nil {
		return x.OutFormat
	}
	return 0
}

func (x *KeyRetreivalRequest) GetCaName() string {
	if x != nil {
		return x.CaName
	}
	return ""
}

type CrlCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaName        string                 `protobuf:"bytes,1,opt,name=ca_name,json=caName,proto3" json:"ca_name,omitempty"`
	SubjectKeyId  string                 `protobuf:"bytes,2,opt,name=subject_key_id,json=subjectKeyId,proto3" json:"subject_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrlCreateRequest) Reset() {
	*x = CrlCreateRequest{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrlCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrlCreateRequest) ProtoMessage() {}

func (x *CrlCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrlCreateRequest.ProtoReflect.Descriptor instead.
func (*CrlCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *CrlCreateRequest) GetCaName() string {
	if x != nil {
		return x.CaName
	}
	return ""
}

func (x *CrlCreateRequest) GetSubjectKeyId() string {
	if x != nil {
		return x.SubjectKeyId
	}
	return ""
}

type CrlRetrievalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaName        string                 `protobuf:"bytes,1,opt,name=ca_name,json=caName,proto3" json:"ca_name,omitempty"`
	CrlNumber     string                 `protobuf:"bytes,2,opt,name=crl_number,json=crlNumber,proto3" json:"crl_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrlRetrievalRequest) Reset() {
	*x = CrlRetrievalRequest{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrlRetrievalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrlRetrievalRequest) ProtoMessage() {}

func (x *CrlRetrievalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrlRetrievalRequest.ProtoReflect.Descriptor instead.
func (*CrlRetrievalRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *CrlRetrievalRequest) GetCaName() string {
	if x != nil {
		return x.CaName
	}
	return ""
}

func (x *CrlRetrievalRequest) GetCrlNumber() string {
	if x != nil {
		return x.CrlNumber
	}
	return ""
}

type CrlListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaName        string                 `protobuf:"bytes,1,opt,name=ca_name,json=caName,proto3" json:"ca_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrlListRequest) Reset() {
	*x = CrlListRequest{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrlListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrlListRequest) ProtoMessage() {}

func (x *CrlListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrlListRequest.ProtoReflect.Descriptor instead.
func (*CrlListRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *CrlListRequest) GetCaName() string {
	if x != nil {
		return x.CaName
	}
	return ""
}

func (x *CrlListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CrlListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CrlReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CrlNumber      string                 `protobuf:"bytes,1,opt,name=crl_number,json=crlNumber,proto3" json:"crl_number,omitempty"`
	IssuerDn       string                 `protobuf:"bytes,2,opt,name=issuer_dn,json=issuerDn,proto3" json:"issuer_dn,omitempty"`
	CaName         string                 `protobuf:"bytes,3,opt,name=ca_name,json=caName,proto3" json:"ca_name,omitempty"`
	AuthorityKeyId string                 `protobuf:"bytes,4,opt,name=authority_key_id,json=authorityKeyId,proto3" json:"authority_key_id,omitempty"`
	CrlPem         string                 `protobuf:"bytes,5,opt,name=crl_pem,json=crlPem,proto3" json:"crl_pem,omitempty"`
	NextUpdate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=next_update,json=nextUpdate,proto3" json:"next_update,omitempty"`
	ThisUpdate     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=this_update,json=thisUpdate,proto3" json:"this_update,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CrlReply) Reset() {
	*x = CrlReply{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrlReply) ProtoMessage() {}

func (x *CrlReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrlReply.ProtoReflect.Descriptor instead.
func (*CrlReply) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *CrlReply) GetCrlNumber() string {
	if x != nil {
		return x.CrlNumber
	}
	return ""
}

func (x *CrlReply) GetIssuerDn() string {
	if x != nil {
		return x.IssuerDn
	}
	return ""
}

func (x *CrlReply) GetCaName() string {
	if x != nil {
		return x.CaName
	}
	return ""
}

func (x *CrlReply) GetAuthorityKeyId() string {
	if x != nil {
		return x.AuthorityKeyId
	}
	return ""
}

func (x *CrlReply) GetCrlPem() string {
	if x != nil {
		return x.CrlPem
	}
	return ""
}

func (x *CrlReply) GetNextUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextUpdate
	}
	return nil
}

func (x *CrlReply) GetThisUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.ThisUpdate
	}
	return nil
}

type CrlListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crls          []*CrlReply            `protobuf:"bytes,1,rep,name=crls,proto3" json:"crls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrlListReply) Reset() {
	*x = CrlListReply{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrlListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrlListReply) ProtoMessage() {}

func (x *CrlListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrlListReply.ProtoReflect.Descriptor instead.
func (*CrlListReply) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *CrlListReply) GetCrls() []*CrlReply {
	if x != nil {
		return x.Crls
	}
	return nil
}

type CertReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Cert          string                 `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertReply) Reset() {
	*x = CertReply{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertReply) ProtoMessage() {}

func (x *CertReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertReply.ProtoReflect.Descriptor instead.
func (*CertReply) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *CertReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CertReply) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

type KeyCertReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Cert          string                 `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"`
	Passphrase    string                 `protobuf:"bytes,4,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyCertReply) Reset() {
	*x = KeyCertReply{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyCertReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyCertReply) ProtoMessage() {}

func (x *KeyCertReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyCertReply.ProtoReflect.Descriptor instead.
func (*KeyCertReply) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *KeyCertReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *KeyCertReply) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyCertReply) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *KeyCertReply) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type CaListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cas           []*CaListReply_Ca      `protobuf:"bytes,1,rep,name=cas,proto3" json:"cas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaListReply) Reset() {
	*x = CaListReply{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaListReply) ProtoMessage() {}

func (x *CaListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaListReply.ProtoReflect.Descriptor instead.
func (*CaListReply) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{22}
}

func (x *CaListReply) GetCas() []*CaListReply_Ca {
	if x != nil {
		return x.Cas
	}
	return nil
}

type CertListReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Certificates      []*CertListReply_Cert  `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	TotalCertCount    int64                  `protobuf:"varint,2,opt,name=total_cert_count,json=totalCertCount,proto3" json:"total_cert_count,omitempty"`
	FilteredCertCount int64                  `protobuf:"varint,3,opt,name=filtered_cert_count,json=filteredCertCount,proto3" json:"filtered_cert_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CertListReply) Reset() {
	*x = CertListReply{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertListReply) ProtoMessage() {}

func (x *CertListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertListReply.ProtoReflect.Descriptor instead.
func (*CertListReply) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{23}
}

func (x *CertListReply) GetCertificates() []*CertListReply_Cert {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *CertListReply) GetTotalCertCount() int64 {
	if x != nil {
		return x.TotalCertCount
	}
	return 0
}

func (x *CertListReply) GetFilteredCertCount() int64 {
	if x != nil {
		return x.FilteredCertCount
	}
	return 0
}

type CertPemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertPemReply) Reset() {
	*x = CertPemReply{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertPemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertPemReply) ProtoMessage() {}

func (x *CertPemReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertPemReply.ProtoReflect.Descriptor instead.
func (*CertPemReply) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *CertPemReply) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

type CaListReply_Ca struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsActive         bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CertSerialNumber string                 `protobuf:"bytes,4,opt,name=cert_serial_number,json=certSerialNumber,proto3" json:"cert_serial_number,omitempty"`
	SubjectKeyId     string                 `protobuf:"bytes,5,opt,name=subject_key_id,json=subjectKeyId,proto3" json:"subject_key_id,omitempty"`
	SubjectName      string                 `protobuf:"bytes,6,opt,name=subject_name,json=subjectName,proto3" json:"subject_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CaListReply_Ca) Reset() {
	*x = CaListReply_Ca{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaListReply_Ca) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaListReply_Ca) ProtoMessage() {}

func (x *CaListReply_Ca) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaListReply_Ca.ProtoReflect.Descriptor instead.
func (*CaListReply_Ca) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{22, 0}
}

func (x *CaListReply_Ca) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CaListReply_Ca) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CaListReply_Ca) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CaListReply_Ca) GetCertSerialNumber() string {
	if x != nil {
		return x.CertSerialNumber
	}
	return ""
}

func (x *CaListReply_Ca) GetSubjectKeyId() string {
	if x != nil {
		return x.SubjectKeyId
	}
	return ""
}

func (x *CaListReply_Ca) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

type CertListReply_Cert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommonName      string                 `protobuf:"bytes,1,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	IssuerDn        string                 `protobuf:"bytes,2,opt,name=issuer_dn,json=issuerDn,proto3" json:"issuer_dn,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	NotBefore       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	CertSerial      string                 `protobuf:"bytes,6,opt,name=cert_serial,json=certSerial,proto3" json:"cert_serial,omitempty"`
	CertFingerprint string                 `protobuf:"bytes,7,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"`
	Sans            []*San                 `protobuf:"bytes,8,rep,name=sans,proto3" json:"sans,omitempty"`
	SigAlgo         string                 `protobuf:"bytes,9,opt,name=sig_algo,json=sigAlgo,proto3" json:"sig_algo,omitempty"`
	KeyLength       int32                  `protobuf:"varint,10,opt,name=key_length,json=keyLength,proto3" json:"key_length,omitempty"`
	CaName          string                 `protobuf:"bytes,11,opt,name=ca_name,json=caName,proto3" json:"ca_name,omitempty"`
	TemplateName    string                 `protobuf:"bytes,12,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CertListReply_Cert) Reset() {
	*x = CertListReply_Cert{}
	mi := &file_proto_rpcca_rpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertListReply_Cert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertListReply_Cert) ProtoMessage() {}

func (x *CertListReply_Cert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcca_rpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertListReply_Cert.ProtoReflect.Descriptor instead.
func (*CertListReply_Cert) Descriptor() ([]byte, []int) {
	return file_proto_rpcca_rpc_proto_rawDescGZIP(), []int{23, 0}
}

func (x *CertListReply_Cert) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *CertListReply_Cert) GetIssuerDn() string {
	if x != nil {
		return x.IssuerDn
	}
	return ""
}

func (x *CertListReply_Cert) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CertListReply_Cert) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertListReply_Cert) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertListReply_Cert) GetCertSerial() string {
	if x != nil {
		return x.CertSerial
	}
	return ""
}

func (x *CertListReply_Cert) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

func (x *CertListReply_Cert) GetSans() []*San {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *CertListReply_Cert) GetSigAlgo() string {
	if x != nil {
		return x.SigAlgo
	}
	return ""
}

func (x *CertListReply_Cert) GetKeyLength() int32 {
	if x != nil {
		return x.KeyLength
	}
	return 0
}

func (x *CertListReply_Cert) GetCaName() string {
	if x != nil {
		return x.CaName
	}
	return ""
}

func (x *CertListReply_Cert) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

var File_proto_rpcca_rpc_proto protoreflect.FileDescriptor

const file_proto_rpcca_rpc_proto_rawDesc = "" +
	"\n" +
	"\x15proto/rpcca_rpc.proto\x12\trpcca_rpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"%\n" +
	"\vSimpleReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"$\n" +
	"\n" +
	"Int64Reply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\"h\n" +
	"\n" +
	"DateFilter\x12,\n" +
	"\x03lte\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03lte\x12,\n" +
	"\x03gte\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03gte\"\x8d\x03\n" +
	"\n" +
	"CertFilter\x12<\n" +
	"\rfilter_fields\x18\x01 \x03(\v2\x17.rpcca_rpc.KeyValueInfoR\ffilterFields\x12A\n" +
	"\x10or_filter_fields\x18\x02 \x03(\v2\x17.rpcca_rpc.KeyValueInfoR\x0eorFilterFields\x12\"\n" +
	"\x04sans\x18\x03 \x03(\v2\x0e.rpcca_rpc.SanR\x04sans\x124\n" +
	"\n" +
	"not_before\x18\x04 \x01(\v2\x15.rpcca_rpc.DateFilterR\tnotBefore\x122\n" +
	"\tnot_after\x18\x05 \x01(\v2\x15.rpcca_rpc.DateFilterR\bnotAfter\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\x05R\x06offset\x12\x19\n" +
	"\border_by\x18\b \x01(\tR\aorderBy\x12'\n" +
	"\x0forder_direction\x18\t \x01(\x05R\x0eorderDirection\"-\n" +
	"\x03San\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\fKeyValueInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"i\n" +
	"\x10BasicConstraints\x12\x13\n" +
	"\x05is_ca\x18\x01 \x01(\bR\x04isCa\x12\x1f\n" +
	"\vpath_length\x18\x02 \x01(\x05R\n" +
	"pathLength\x12\x1f\n" +
	"\vis_critical\x18\x03 \x01(\bR\n" +
	"isCritical\"|\n" +
	"\x11CertImportRequest\x12\x17\n" +
	"\aca_name\x18\x01 \x01(\tR\x06caName\x12\x19\n" +
	"\bcert_pem\x18\x02 \x01(\tR\acertPem\x123\n" +
	"\bmetadata\x18\x03 \x03(\v2\x17.rpcca_rpc.KeyValueInfoR\bmetadata\"\xa9\x04\n" +
	"\vCertRequest\x12\x16\n" +
	"\x06pkcs10\x18\x01 \x01(\tR\x06pkcs10\x12\x17\n" +
	"\aca_name\x18\x02 \x01(\tR\x06caName\x12\"\n" +
	"\x04sans\x18\x03 \x03(\v2\x0e.rpcca_rpc.SanR\x04sans\x129\n" +
	"\n" +
	"not_before\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x19\n" +
	"\bkey_size\x18\b \x01(\x05R\akeySize\x12\x1f\n" +
	"\vcommon_name\x18\t \x01(\tR\n" +
	"commonName\x12,\n" +
	"\x12extended_key_usage\x18\v \x03(\tR\x10extendedKeyUsage\x12#\n" +
	"\rtemplate_name\x18\f \x01(\tR\ftemplateName\x12/\n" +
	"\x06kvinfo\x18\r \x03(\v2\x17.rpcca_rpc.KeyValueInfoR\x06kvinfo\x12,\n" +
	"\x11KeyConstraintsStr\x18\x0e \x03(\tR\x11KeyConstraintsStr\x12H\n" +
	"\x11basic_constraints\x18\x0f \x01(\v2\x1b.rpcca_rpc.BasicConstraintsR\x10basicConstraints\x12\x19\n" +
	"\bkey_type\x18\x10 \x01(\tR\akeyType\"C\n" +
	"\x16CertificateFingerprint\x12)\n" +
	"\x10cert_fingerprint\x18\x01 \x01(\tR\x0fcertFingerprint\"\xc6\x04\n" +
	"\vCertificate\x12\x1f\n" +
	"\vcommon_name\x18\x01 \x01(\tR\n" +
	"commonName\x12\x1b\n" +
	"\tissuer_dn\x18\x02 \x01(\tR\bissuerDn\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"not_before\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x1f\n" +
	"\vcert_serial\x18\x06 \x01(\tR\n" +
	"certSerial\x12)\n" +
	"\x10cert_fingerprint\x18\a \x01(\tR\x0fcertFingerprint\x12\"\n" +
	"\x04sans\x18\b \x03(\v2\x0e.rpcca_rpc.SanR\x04sans\x12\x19\n" +
	"\bsig_algo\x18\t \x01(\tR\asigAlgo\x12\x1d\n" +
	"\n" +
	"key_length\x18\n" +
	" \x01(\x05R\tkeyLength\x12\x17\n" +
	"\aca_name\x18\v \x01(\tR\x06caName\x12#\n" +
	"\rtemplate_name\x18\f \x01(\tR\ftemplateName\x12\x1f\n" +
	"\vcert_string\x18\r \x01(\tR\n" +
	"certString\x12\x12\n" +
	"\x04cdps\x18\x0e \x03(\tR\x04cdps\x123\n" +
	"\bmetadata\x18\x0f \x03(\v2\x17.rpcca_rpc.KeyValueInfoR\bmetadata\x12\x1b\n" +
	"\tissued_dn\x18\x10 \x01(\tR\bissuedDn\"=\n" +
	"\x0fCertificateList\x12*\n" +
	"\x04cert\x18\x01 \x03(\v2\x16.rpcca_rpc.CertificateR\x04cert\"\xc9\x01\n" +
	"\x11RevokeCertRequest\x12\x17\n" +
	"\aca_name\x18\x01 \x01(\tR\x06caName\x12)\n" +
	"\x10cert_fingerprint\x18\x02 \x01(\tR\x0fcertFingerprint\x12+\n" +
	"\x11revocation_reason\x18\x03 \x01(\tR\x10revocationReason\x12C\n" +
	"\x0frevocation_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0erevocationDate\"\xa1\x01\n" +
	"\x13KeyRetreivalRequest\x12)\n" +
	"\x10cert_fingerprint\x18\x01 \x01(\tR\x0fcertFingerprint\x12'\n" +
	"\x0fpassphrase_hash\x18\x02 \x01(\tR\x0epassphraseHash\x12\x1d\n" +
	"\n" +
	"out_format\x18\x03 \x01(\x05R\toutFormat\x12\x17\n" +
	"\aca_name\x18\x04 \x01(\tR\x06caName\"Q\n" +
	"\x10CrlCreateRequest\x12\x17\n" +
	"\aca_name\x18\x01 \x01(\tR\x06caName\x12$\n" +
	"\x0esubject_key_id\x18\x02 \x01(\tR\fsubjectKeyId\"M\n" +
	"\x13CrlRetrievalRequest\x12\x17\n" +
	"\aca_name\x18\x01 \x01(\tR\x06caName\x12\x1d\n" +
	"\n" +
	"crl_number\x18\x02 \x01(\tR\tcrlNumber\"W\n" +
	"\x0eCrlListRequest\x12\x17\n" +
	"\aca_name\x18\x01 \x01(\tR\x06caName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x9c\x02\n" +
	"\bCrlReply\x12\x1d\n" +
	"\n" +
	"crl_number\x18\x01 \x01(\tR\tcrlNumber\x12\x1b\n" +
	"\tissuer_dn\x18\x02 \x01(\tR\bissuerDn\x12\x17\n" +
	"\aca_name\x18\x03 \x01(\tR\x06caName\x12(\n" +
	"\x10authority_key_id\x18\x04 \x01(\tR\x0eauthorityKeyId\x12\x17\n" +
	"\acrl_pem\x18\x05 \x01(\tR\x06crlPem\x12;\n" +
	"\vnext_update\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"nextUpdate\x12;\n" +
	"\vthis_update\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"thisUpdate\"7\n" +
	"\fCrlListReply\x12'\n" +
	"\x04crls\x18\x01 \x03(\v2\x13.rpcca_rpc.CrlReplyR\x04crls\"7\n" +
	"\tCertReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x12\n" +
	"\x04cert\x18\x02 \x01(\tR\x04cert\"l\n" +
	"\fKeyCertReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04cert\x18\x03 \x01(\tR\x04cert\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x04 \x01(\tR\n" +
	"passphrase\"\xf9\x01\n" +
	"\vCaListReply\x12+\n" +
	"\x03cas\x18\x01 \x03(\v2\x19.rpcca_rpc.CaListReply.CaR\x03cas\x1a\xbc\x01\n" +
	"\x02Ca\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12,\n" +
	"\x12cert_serial_number\x18\x04 \x01(\tR\x10certSerialNumber\x12$\n" +
	"\x0esubject_key_id\x18\x05 \x01(\tR\fsubjectKeyId\x12!\n" +
	"\fsubject_name\x18\x06 \x01(\tR\vsubjectName\"\xe7\x04\n" +
	"\rCertListReply\x12A\n" +
	"\fcertificates\x18\x01 \x03(\v2\x1d.rpcca_rpc.CertListReply.CertR\fcertificates\x12(\n" +
	"\x10total_cert_count\x18\x02 \x01(\x03R\x0etotalCertCount\x12.\n" +
	"\x13filtered_cert_count\x18\x03 \x01(\x03R\x11filteredCertCount\x1a\xb8\x03\n" +
	"\x04Cert\x12\x1f\n" +
	"\vcommon_name\x18\x01 \x01(\tR\n" +
	"commonName\x12\x1b\n" +
	"\tissuer_dn\x18\x02 \x01(\tR\bissuerDn\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"not_before\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x1f\n" +
	"\vcert_serial\x18\x06 \x01(\tR\n" +
	"certSerial\x12)\n" +
	"\x10cert_fingerprint\x18\a \x01(\tR\x0fcertFingerprint\x12\"\n" +
	"\x04sans\x18\b \x03(\v2\x0e.rpcca_rpc.SanR\x04sans\x12\x19\n" +
	"\bsig_algo\x18\t \x01(\tR\asigAlgo\x12\x1d\n" +
	"\n" +
	"key_length\x18\n" +
	" \x01(\x05R\tkeyLength\x12\x17\n" +
	"\aca_name\x18\v \x01(\tR\x06caName\x12#\n" +
	"\rtemplate_name\x18\f \x01(\tR\ftemplateName\")\n" +
	"\fCertPemReply\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem2\xae\b\n" +
	"\tRPCCA_RPC\x12A\n" +
	"\x13GetConfiguredCaList\x12\x10.rpcca_rpc.Empty\x1a\x16.rpcca_rpc.CaListReply\"\x00\x12>\n" +
	"\fGetCertCount\x12\x15.rpcca_rpc.CertFilter\x1a\x15.rpcca_rpc.Int64Reply\"\x00\x12@\n" +
	"\vGetCertList\x12\x15.rpcca_rpc.CertFilter\x1a\x18.rpcca_rpc.CertListReply\"\x00\x12J\n" +
	"\n" +
	"GetCertPem\x12!.rpcca_rpc.CertificateFingerprint\x1a\x17.rpcca_rpc.CertPemReply\"\x00\x12G\n" +
	"\n" +
	"GetPrivKey\x12\x1e.rpcca_rpc.KeyRetreivalRequest\x1a\x17.rpcca_rpc.KeyCertReply\"\x00\x12B\n" +
	"\tCreateCrl\x12\x1b.rpcca_rpc.CrlCreateRequest\x1a\x16.rpcca_rpc.SimpleReply\"\x00\x12?\n" +
	"\x06GetCrl\x12\x1e.rpcca_rpc.CrlRetrievalRequest\x1a\x13.rpcca_rpc.CrlReply\"\x00\x12B\n" +
	"\n" +
	"GetCrlList\x12\x19.rpcca_rpc.CrlListRequest\x1a\x17.rpcca_rpc.CrlListReply\"\x00\x12M\n" +
	"\x0eGetCertDetails\x12!.rpcca_rpc.CertificateFingerprint\x1a\x16.rpcca_rpc.Certificate\"\x00\x12I\n" +
	"\x16GetCertDetailsByFilter\x12\x15.rpcca_rpc.CertFilter\x1a\x16.rpcca_rpc.Certificate\"\x00\x12T\n" +
	"\x11GetCaChainForCert\x12!.rpcca_rpc.CertificateFingerprint\x1a\x1a.rpcca_rpc.CertificateList\"\x00\x12D\n" +
	"\n" +
	"ImportCert\x12\x1c.rpcca_rpc.CertImportRequest\x1a\x16.rpcca_rpc.SimpleReply\"\x00\x12=\n" +
	"\vRequestCert\x12\x16.rpcca_rpc.CertRequest\x1a\x14.rpcca_rpc.CertReply\"\x00\x12C\n" +
	"\x0eRequestKeyCert\x12\x16.rpcca_rpc.CertRequest\x1a\x17.rpcca_rpc.KeyCertReply\"\x00\x12D\n" +
	"\n" +
	"RevokeCert\x12\x1c.rpcca_rpc.RevokeCertRequest\x1a\x16.rpcca_rpc.SimpleReply\"\x00B\fZ\n" +
	"rpcserver/b\x06proto3"

var (
	file_proto_rpcca_rpc_proto_rawDescOnce sync.Once
	file_proto_rpcca_rpc_proto_rawDescData []byte
)

func file_proto_rpcca_rpc_proto_rawDescGZIP() []byte {
	file_proto_rpcca_rpc_proto_rawDescOnce.Do(func() {
		file_proto_rpcca_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rpcca_rpc_proto_rawDesc), len(file_proto_rpcca_rpc_proto_rawDesc)))
	})
	return file_proto_rpcca_rpc_proto_rawDescData
}

var file_proto_rpcca_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_rpcca_rpc_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: rpcca_rpc.Empty
	(*SimpleReply)(nil),            // 1: rpcca_rpc.SimpleReply
	(*Int64Reply)(nil),             // 2: rpcca_rpc.Int64Reply
	(*DateFilter)(nil),             // 3: rpcca_rpc.DateFilter
	(*CertFilter)(nil),             // 4: rpcca_rpc.CertFilter
	(*San)(nil),                    // 5: rpcca_rpc.San
	(*KeyValueInfo)(nil),           // 6: rpcca_rpc.KeyValueInfo
	(*BasicConstraints)(nil),       // 7: rpcca_rpc.BasicConstraints
	(*CertImportRequest)(nil),      // 8: rpcca_rpc.CertImportRequest
	(*CertRequest)(nil),            // 9: rpcca_rpc.CertRequest
	(*CertificateFingerprint)(nil), // 10: rpcca_rpc.CertificateFingerprint
	(*Certificate)(nil),            // 11: rpcca_rpc.Certificate
	(*CertificateList)(nil),        // 12: rpcca_rpc.CertificateList
	(*RevokeCertRequest)(nil),      // 13: rpcca_rpc.RevokeCertRequest
	(*KeyRetreivalRequest)(nil),    // 14: rpcca_rpc.KeyRetreivalRequest
	(*CrlCreateRequest)(nil),       // 15: rpcca_rpc.CrlCreateRequest
	(*CrlRetrievalRequest)(nil),    // 16: rpcca_rpc.CrlRetrievalRequest
	(*CrlListRequest)(nil),         // 17: rpcca_rpc.CrlListRequest
	(*CrlReply)(nil),               // 18: rpcca_rpc.CrlReply
	(*CrlListReply)(nil),           // 19: rpcca_rpc.CrlListReply
	(*CertReply)(nil),              // 20: rpcca_rpc.CertReply
	(*KeyCertReply)(nil),           // 21: rpcca_rpc.KeyCertReply
	(*CaListReply)(nil),            // 22: rpcca_rpc.CaListReply
	(*CertListReply)(nil),          // 23: rpcca_rpc.CertListReply
	(*CertPemReply)(nil),           // 24: rpcca_rpc.CertPemReply
	(*CaListReply_Ca)(nil),         // 25: rpcca_rpc.CaListReply.Ca
	(*CertListReply_Cert)(nil),     // 26: rpcca_rpc.CertListReply.Cert
	(*timestamppb.Timestamp)(nil),  // 27: google.protobuf.Timestamp
}
var file_proto_rpcca_rpc_proto_depIdxs = []int32{
	27, // 0: rpcca_rpc.DateFilter.lte:type_name -> google.protobuf.Timestamp
	27, // 1: rpcca_rpc.DateFilter.gte:type_name -> google.protobuf.Timestamp
	6,  // 2: rpcca_rpc.CertFilter.filter_fields:type_name -> rpcca_rpc.KeyValueInfo
	6,  // 3: rpcca_rpc.CertFilter.or_filter_fields:type_name -> rpcca_rpc.KeyValueInfo
	5,  // 4: rpcca_rpc.CertFilter.sans:type_name -> rpcca_rpc.San
	3,  // 5: rpcca_rpc.CertFilter.not_before:type_name -> rpcca_rpc.DateFilter
	3,  // 6: rpcca_rpc.CertFilter.not_after:type_name -> rpcca_rpc.DateFilter
	6,  // 7: rpcca_rpc.CertImportRequest.metadata:type_name -> rpcca_rpc.KeyValueInfo
	5,  // 8: rpcca_rpc.CertRequest.sans:type_name -> rpcca_rpc.San
	27, // 9: rpcca_rpc.CertRequest.not_before:type_name -> google.protobuf.Timestamp
	27, // 10: rpcca_rpc.CertRequest.not_after:type_name -> google.protobuf.Timestamp
	6,  // 11: rpcca_rpc.CertRequest.kvinfo:type_name -> rpcca_rpc.KeyValueInfo
	7,  // 12: rpcca_rpc.CertRequest.basic_constraints:type_name -> rpcca_rpc.BasicConstraints
	27, // 13: rpcca_rpc.Certificate.not_before:type_name -> google.protobuf.Timestamp
	27, // 14: rpcca_rpc.Certificate.not_after:type_name -> google.protobuf.Timestamp
	5,  // 15: rpcca_rpc.Certificate.sans:type_name -> rpcca_rpc.San
	6,  // 16: rpcca_rpc.Certificate.metadata:type_name -> rpcca_rpc.KeyValueInfo
	11, // 17: rpcca_rpc.CertificateList.cert:type_name -> rpcca_rpc.Certificate
	27, // 18: rpcca_rpc.RevokeCertRequest.revocation_date:type_name -> google.protobuf.Timestamp
	27, // 19: rpcca_rpc.CrlReply.next_update:type_name -> google.protobuf.Timestamp
	27, // 20: rpcca_rpc.CrlReply.this_update:type_name -> google.protobuf.Timestamp
	18, // 21: rpcca_rpc.CrlListReply.crls:type_name -> rpcca_rpc.CrlReply
	25, // 22: rpcca_rpc.CaListReply.cas:type_name -> rpcca_rpc.CaListReply.Ca
	26, // 23: rpcca_rpc.CertListReply.certificates:type_name -> rpcca_rpc.CertListReply.Cert
	27, // 24: rpcca_rpc.CertListReply.Cert.not_before:type_name -> google.protobuf.Timestamp
	27, // 25: rpcca_rpc.CertListReply.Cert.not_after:type_name -> google.protobuf.Timestamp
	5,  // 26: rpcca_rpc.CertListReply.Cert.sans:type_name -> rpcca_rpc.San
	0,  // 27: rpcca_rpc.RPCCA_RPC.GetConfiguredCaList:input_type -> rpcca_rpc.Empty
	4,  // 28: rpcca_rpc.RPCCA_RPC.GetCertCount:input_type -> rpcca_rpc.CertFilter
	4,  // 29: rpcca_rpc.RPCCA_RPC.GetCertList:input_type -> rpcca_rpc.CertFilter
	10, // 30: rpcca_rpc.RPCCA_RPC.GetCertPem:input_type -> rpcca_rpc.CertificateFingerprint
	14, // 31: rpcca_rpc.RPCCA_RPC.GetPrivKey:input_type -> rpcca_rpc.KeyRetreivalRequest
	15, // 32: rpcca_rpc.RPCCA_RPC.CreateCrl:input_type -> rpcca_rpc.CrlCreateRequest
	16, // 33: rpcca_rpc.RPCCA_RPC.GetCrl:input_type -> rpcca_rpc.CrlRetrievalRequest
	17, // 34: rpcca_rpc.RPCCA_RPC.GetCrlList:input_type -> rpcca_rpc.CrlListRequest
	10, // 35: rpcca_rpc.RPCCA_RPC.GetCertDetails:input_type -> rpcca_rpc.CertificateFingerprint
	4,  // 36: rpcca_rpc.RPCCA_RPC.GetCertDetailsByFilter:input_type -> rpcca_rpc.CertFilter
	10, // 37: rpcca_rpc.RPCCA_RPC.GetCaChainForCert:input_type -> rpcca_rpc.CertificateFingerprint
	8,  // 38: rpcca_rpc.RPCCA_RPC.ImportCert:input_type -> rpcca_rpc.CertImportRequest
	9,  // 39: rpcca_rpc.RPCCA_RPC.RequestCert:input_type -> rpcca_rpc.CertRequest
	9,  // 40: rpcca_rpc.RPCCA_RPC.RequestKeyCert:input_type -> rpcca_rpc.CertRequest
	13, // 41: rpcca_rpc.RPCCA_RPC.RevokeCert:input_type -> rpcca_rpc.RevokeCertRequest
	22, // 42: rpcca_rpc.RPCCA_RPC.GetConfiguredCaList:output_type -> rpcca_rpc.CaListReply
	2,  // 43: rpcca_rpc.RPCCA_RPC.GetCertCount:output_type -> rpcca_rpc.Int64Reply
	23, // 44: rpcca_rpc.RPCCA_RPC.GetCertList:output_type -> rpcca_rpc.CertListReply
	24, // 45: rpcca_rpc.RPCCA_RPC.GetCertPem:output_type -> rpcca_rpc.CertPemReply
	21, // 46: rpcca_rpc.RPCCA_RPC.GetPrivKey:output_type -> rpcca_rpc.KeyCertReply
	1,  // 47: rpcca_rpc.RPCCA_RPC.CreateCrl:output_type -> rpcca_rpc.SimpleReply
	18, // 48: rpcca_rpc.RPCCA_RPC.GetCrl:output_type -> rpcca_rpc.CrlReply
	19, // 49: rpcca_rpc.RPCCA_RPC.GetCrlList:output_type -> rpcca_rpc.CrlListReply
	11, // 50: rpcca_rpc.RPCCA_RPC.GetCertDetails:output_type -> rpcca_rpc.Certificate
	11, // 51: rpcca_rpc.RPCCA_RPC.GetCertDetailsByFilter:output_type -> rpcca_rpc.Certificate
	12, // 52: rpcca_rpc.RPCCA_RPC.GetCaChainForCert:output_type -> rpcca_rpc.CertificateList
	1,  // 53: rpcca_rpc.RPCCA_RPC.ImportCert:output_type -> rpcca_rpc.SimpleReply
	20, // 54: rpcca_rpc.RPCCA_RPC.RequestCert:output_type -> rpcca_rpc.CertReply
	21, // 55: rpcca_rpc.RPCCA_RPC.RequestKeyCert:output_type -> rpcca_rpc.KeyCertReply
	1,  // 56: rpcca_rpc.RPCCA_RPC.RevokeCert:output_type -> rpcca_rpc.SimpleReply
	42, // [42:57] is the sub-list for method output_type
	27, // [27:42] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_rpcca_rpc_proto_init() }
func file_proto_rpcca_rpc_proto_init() {
	if File_proto_rpcca_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rpcca_rpc_proto_rawDesc), len(file_proto_rpcca_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rpcca_rpc_proto_goTypes,
		DependencyIndexes: file_proto_rpcca_rpc_proto_depIdxs,
		MessageInfos:      file_proto_rpcca_rpc_proto_msgTypes,
	}.Build()
	File_proto_rpcca_rpc_proto = out.File
	file_proto_rpcca_rpc_proto_goTypes = nil
	file_proto_rpcca_rpc_proto_depIdxs = nil
}
