// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: proto/rpcca_rpc.proto

package rpcserver

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPCCA_RPC_GetConfiguredCaList_FullMethodName    = "/rpcca_rpc.RPCCA_RPC/GetConfiguredCaList"
	RPCCA_RPC_GetCertCount_FullMethodName           = "/rpcca_rpc.RPCCA_RPC/GetCertCount"
	RPCCA_RPC_GetCertList_FullMethodName            = "/rpcca_rpc.RPCCA_RPC/GetCertList"
	RPCCA_RPC_GetCertPem_FullMethodName             = "/rpcca_rpc.RPCCA_RPC/GetCertPem"
	RPCCA_RPC_GetPrivKey_FullMethodName             = "/rpcca_rpc.RPCCA_RPC/GetPrivKey"
	RPCCA_RPC_CreateCrl_FullMethodName              = "/rpcca_rpc.RPCCA_RPC/CreateCrl"
	RPCCA_RPC_GetCrl_FullMethodName                 = "/rpcca_rpc.RPCCA_RPC/GetCrl"
	RPCCA_RPC_GetCrlList_FullMethodName             = "/rpcca_rpc.RPCCA_RPC/GetCrlList"
	RPCCA_RPC_GetCertDetails_FullMethodName         = "/rpcca_rpc.RPCCA_RPC/GetCertDetails"
	RPCCA_RPC_GetCertDetailsByFilter_FullMethodName = "/rpcca_rpc.RPCCA_RPC/GetCertDetailsByFilter"
	RPCCA_RPC_GetCaChainForCert_FullMethodName      = "/rpcca_rpc.RPCCA_RPC/GetCaChainForCert"
	RPCCA_RPC_ImportCert_FullMethodName             = "/rpcca_rpc.RPCCA_RPC/ImportCert"
	RPCCA_RPC_RequestCert_FullMethodName            = "/rpcca_rpc.RPCCA_RPC/RequestCert"
	RPCCA_RPC_RequestKeyCert_FullMethodName         = "/rpcca_rpc.RPCCA_RPC/RequestKeyCert"
	RPCCA_RPC_RevokeCert_FullMethodName             = "/rpcca_rpc.RPCCA_RPC/RevokeCert"
)

// RPCCA_RPCClient is the client API for RPCCA_RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCCA_RPCClient interface {
	GetConfiguredCaList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CaListReply, error)
	// rpc calls for retrieving certificates and keys
	GetCertCount(ctx context.Context, in *CertFilter, opts ...grpc.CallOption) (*Int64Reply, error)
	GetCertList(ctx context.Context, in *CertFilter, opts ...grpc.CallOption) (*CertListReply, error)
	GetCertPem(ctx context.Context, in *CertificateFingerprint, opts ...grpc.CallOption) (*CertPemReply, error)
	GetPrivKey(ctx context.Context, in *KeyRetreivalRequest, opts ...grpc.CallOption) (*KeyCertReply, error)
	CreateCrl(ctx context.Context, in *CrlCreateRequest, opts ...grpc.CallOption) (*SimpleReply, error)
	GetCrl(ctx context.Context, in *CrlRetrievalRequest, opts ...grpc.CallOption) (*CrlReply, error)
	GetCrlList(ctx context.Context, in *CrlListRequest, opts ...grpc.CallOption) (*CrlListReply, error)
	GetCertDetails(ctx context.Context, in *CertificateFingerprint, opts ...grpc.CallOption) (*Certificate, error)
	GetCertDetailsByFilter(ctx context.Context, in *CertFilter, opts ...grpc.CallOption) (*Certificate, error)
	GetCaChainForCert(ctx context.Context, in *CertificateFingerprint, opts ...grpc.CallOption) (*CertificateList, error)
	// rpc calls for cert management
	ImportCert(ctx context.Context, in *CertImportRequest, opts ...grpc.CallOption) (*SimpleReply, error)
	RequestCert(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertReply, error)
	RequestKeyCert(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*KeyCertReply, error)
	RevokeCert(ctx context.Context, in *RevokeCertRequest, opts ...grpc.CallOption) (*SimpleReply, error)
}

type rPCCA_RPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCCA_RPCClient(cc grpc.ClientConnInterface) RPCCA_RPCClient {
	return &rPCCA_RPCClient{cc}
}

func (c *rPCCA_RPCClient) GetConfiguredCaList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CaListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaListReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_GetConfiguredCaList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) GetCertCount(ctx context.Context, in *CertFilter, opts ...grpc.CallOption) (*Int64Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Int64Reply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_GetCertCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) GetCertList(ctx context.Context, in *CertFilter, opts ...grpc.CallOption) (*CertListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertListReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_GetCertList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) GetCertPem(ctx context.Context, in *CertificateFingerprint, opts ...grpc.CallOption) (*CertPemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertPemReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_GetCertPem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) GetPrivKey(ctx context.Context, in *KeyRetreivalRequest, opts ...grpc.CallOption) (*KeyCertReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyCertReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_GetPrivKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) CreateCrl(ctx context.Context, in *CrlCreateRequest, opts ...grpc.CallOption) (*SimpleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_CreateCrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) GetCrl(ctx context.Context, in *CrlRetrievalRequest, opts ...grpc.CallOption) (*CrlReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrlReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_GetCrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) GetCrlList(ctx context.Context, in *CrlListRequest, opts ...grpc.CallOption) (*CrlListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrlListReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_GetCrlList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) GetCertDetails(ctx context.Context, in *CertificateFingerprint, opts ...grpc.CallOption) (*Certificate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Certificate)
	err := c.cc.Invoke(ctx, RPCCA_RPC_GetCertDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) GetCertDetailsByFilter(ctx context.Context, in *CertFilter, opts ...grpc.CallOption) (*Certificate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Certificate)
	err := c.cc.Invoke(ctx, RPCCA_RPC_GetCertDetailsByFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) GetCaChainForCert(ctx context.Context, in *CertificateFingerprint, opts ...grpc.CallOption) (*CertificateList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateList)
	err := c.cc.Invoke(ctx, RPCCA_RPC_GetCaChainForCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) ImportCert(ctx context.Context, in *CertImportRequest, opts ...grpc.CallOption) (*SimpleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_ImportCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) RequestCert(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_RequestCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) RequestKeyCert(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*KeyCertReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyCertReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_RequestKeyCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCA_RPCClient) RevokeCert(ctx context.Context, in *RevokeCertRequest, opts ...grpc.CallOption) (*SimpleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleReply)
	err := c.cc.Invoke(ctx, RPCCA_RPC_RevokeCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCCA_RPCServer is the server API for RPCCA_RPC service.
// All implementations must embed UnimplementedRPCCA_RPCServer
// for forward compatibility.
type RPCCA_RPCServer interface {
	GetConfiguredCaList(context.Context, *Empty) (*CaListReply, error)
	// rpc calls for retrieving certificates and keys
	GetCertCount(context.Context, *CertFilter) (*Int64Reply, error)
	GetCertList(context.Context, *CertFilter) (*CertListReply, error)
	GetCertPem(context.Context, *CertificateFingerprint) (*CertPemReply, error)
	GetPrivKey(context.Context, *KeyRetreivalRequest) (*KeyCertReply, error)
	CreateCrl(context.Context, *CrlCreateRequest) (*SimpleReply, error)
	GetCrl(context.Context, *CrlRetrievalRequest) (*CrlReply, error)
	GetCrlList(context.Context, *CrlListRequest) (*CrlListReply, error)
	GetCertDetails(context.Context, *CertificateFingerprint) (*Certificate, error)
	GetCertDetailsByFilter(context.Context, *CertFilter) (*Certificate, error)
	GetCaChainForCert(context.Context, *CertificateFingerprint) (*CertificateList, error)
	// rpc calls for cert management
	ImportCert(context.Context, *CertImportRequest) (*SimpleReply, error)
	RequestCert(context.Context, *CertRequest) (*CertReply, error)
	RequestKeyCert(context.Context, *CertRequest) (*KeyCertReply, error)
	RevokeCert(context.Context, *RevokeCertRequest) (*SimpleReply, error)
	mustEmbedUnimplementedRPCCA_RPCServer()
}

// UnimplementedRPCCA_RPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPCCA_RPCServer struct{}

func (UnimplementedRPCCA_RPCServer) GetConfiguredCaList(context.Context, *Empty) (*CaListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfiguredCaList not implemented")
}
func (UnimplementedRPCCA_RPCServer) GetCertCount(context.Context, *CertFilter) (*Int64Reply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertCount not implemented")
}
func (UnimplementedRPCCA_RPCServer) GetCertList(context.Context, *CertFilter) (*CertListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertList not implemented")
}
func (UnimplementedRPCCA_RPCServer) GetCertPem(context.Context, *CertificateFingerprint) (*CertPemReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertPem not implemented")
}
func (UnimplementedRPCCA_RPCServer) GetPrivKey(context.Context, *KeyRetreivalRequest) (*KeyCertReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrivKey not implemented")
}
func (UnimplementedRPCCA_RPCServer) CreateCrl(context.Context, *CrlCreateRequest) (*SimpleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCrl not implemented")
}
func (UnimplementedRPCCA_RPCServer) GetCrl(context.Context, *CrlRetrievalRequest) (*CrlReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCrl not implemented")
}
func (UnimplementedRPCCA_RPCServer) GetCrlList(context.Context, *CrlListRequest) (*CrlListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCrlList not implemented")
}
func (UnimplementedRPCCA_RPCServer) GetCertDetails(context.Context, *CertificateFingerprint) (*Certificate, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertDetails not implemented")
}
func (UnimplementedRPCCA_RPCServer) GetCertDetailsByFilter(context.Context, *CertFilter) (*Certificate, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertDetailsByFilter not implemented")
}
func (UnimplementedRPCCA_RPCServer) GetCaChainForCert(context.Context, *CertificateFingerprint) (*CertificateList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCaChainForCert not implemented")
}
func (UnimplementedRPCCA_RPCServer) ImportCert(context.Context, *CertImportRequest) (*SimpleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportCert not implemented")
}
func (UnimplementedRPCCA_RPCServer) RequestCert(context.Context, *CertRequest) (*CertReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCert not implemented")
}
func (UnimplementedRPCCA_RPCServer) RequestKeyCert(context.Context, *CertRequest) (*KeyCertReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestKeyCert not implemented")
}
func (UnimplementedRPCCA_RPCServer) RevokeCert(context.Context, *RevokeCertRequest) (*SimpleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCert not implemented")
}
func (UnimplementedRPCCA_RPCServer) mustEmbedUnimplementedRPCCA_RPCServer() {}
func (UnimplementedRPCCA_RPCServer) testEmbeddedByValue()                   {}

// UnsafeRPCCA_RPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCCA_RPCServer will
// result in compilation errors.
type UnsafeRPCCA_RPCServer interface {
	mustEmbedUnimplementedRPCCA_RPCServer()
}

func RegisterRPCCA_RPCServer(s grpc.ServiceRegistrar, srv RPCCA_RPCServer) {
	// If the following call panics, it indicates UnimplementedRPCCA_RPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPCCA_RPC_ServiceDesc, srv)
}

func _RPCCA_RPC_GetConfiguredCaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).GetConfiguredCaList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_GetConfiguredCaList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).GetConfiguredCaList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_GetCertCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).GetCertCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_GetCertCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).GetCertCount(ctx, req.(*CertFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_GetCertList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).GetCertList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_GetCertList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).GetCertList(ctx, req.(*CertFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_GetCertPem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateFingerprint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).GetCertPem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_GetCertPem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).GetCertPem(ctx, req.(*CertificateFingerprint))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_GetPrivKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRetreivalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).GetPrivKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_GetPrivKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).GetPrivKey(ctx, req.(*KeyRetreivalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_CreateCrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrlCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).CreateCrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_CreateCrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).CreateCrl(ctx, req.(*CrlCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_GetCrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrlRetrievalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).GetCrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_GetCrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).GetCrl(ctx, req.(*CrlRetrievalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_GetCrlList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrlListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).GetCrlList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_GetCrlList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).GetCrlList(ctx, req.(*CrlListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_GetCertDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateFingerprint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).GetCertDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_GetCertDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).GetCertDetails(ctx, req.(*CertificateFingerprint))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_GetCertDetailsByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).GetCertDetailsByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_GetCertDetailsByFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).GetCertDetailsByFilter(ctx, req.(*CertFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_GetCaChainForCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateFingerprint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).GetCaChainForCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_GetCaChainForCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).GetCaChainForCert(ctx, req.(*CertificateFingerprint))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_ImportCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).ImportCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_ImportCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).ImportCert(ctx, req.(*CertImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_RequestCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).RequestCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_RequestCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).RequestCert(ctx, req.(*CertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_RequestKeyCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).RequestKeyCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_RequestKeyCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).RequestKeyCert(ctx, req.(*CertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCA_RPC_RevokeCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCA_RPCServer).RevokeCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCCA_RPC_RevokeCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCA_RPCServer).RevokeCert(ctx, req.(*RevokeCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCCA_RPC_ServiceDesc is the grpc.ServiceDesc for RPCCA_RPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCCA_RPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcca_rpc.RPCCA_RPC",
	HandlerType: (*RPCCA_RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfiguredCaList",
			Handler:    _RPCCA_RPC_GetConfiguredCaList_Handler,
		},
		{
			MethodName: "GetCertCount",
			Handler:    _RPCCA_RPC_GetCertCount_Handler,
		},
		{
			MethodName: "GetCertList",
			Handler:    _RPCCA_RPC_GetCertList_Handler,
		},
		{
			MethodName: "GetCertPem",
			Handler:    _RPCCA_RPC_GetCertPem_Handler,
		},
		{
			MethodName: "GetPrivKey",
			Handler:    _RPCCA_RPC_GetPrivKey_Handler,
		},
		{
			MethodName: "CreateCrl",
			Handler:    _RPCCA_RPC_CreateCrl_Handler,
		},
		{
			MethodName: "GetCrl",
			Handler:    _RPCCA_RPC_GetCrl_Handler,
		},
		{
			MethodName: "GetCrlList",
			Handler:    _RPCCA_RPC_GetCrlList_Handler,
		},
		{
			MethodName: "GetCertDetails",
			Handler:    _RPCCA_RPC_GetCertDetails_Handler,
		},
		{
			MethodName: "GetCertDetailsByFilter",
			Handler:    _RPCCA_RPC_GetCertDetailsByFilter_Handler,
		},
		{
			MethodName: "GetCaChainForCert",
			Handler:    _RPCCA_RPC_GetCaChainForCert_Handler,
		},
		{
			MethodName: "ImportCert",
			Handler:    _RPCCA_RPC_ImportCert_Handler,
		},
		{
			MethodName: "RequestCert",
			Handler:    _RPCCA_RPC_RequestCert_Handler,
		},
		{
			MethodName: "RequestKeyCert",
			Handler:    _RPCCA_RPC_RequestKeyCert_Handler,
		},
		{
			MethodName: "RevokeCert",
			Handler:    _RPCCA_RPC_RevokeCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpcca_rpc.proto",
}
